# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='author',
            field=models.CharField(help_text='full Name', max_length=60),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='content',
            field=models.TextField(help_text='Write something you wish to write!'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='title',
            field=models.CharField(help_text='write beautiful title of your blog', max_length=140),
        ),
    ]
