# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20160702_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
